name: Push Image to Docker Hub

on:
  workflow_run:
    workflows: ['Build Docker Image']
    types:
      - completed
  workflow_dispatch:

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker - login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Download Docker Image (Artifact)
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: build/artifacts

      - name: Push Docker Image
        run: |
          cd build/artifacts
          docker load < docker-image.tar
          export DOCKER_FULLTAG=gayankanishka/pizza-castle-menu-service:dev-${GIT_SHA:0:7}-$(date +%s)
          docker image tag gayankanishka/pizza-castle-menu-service ${DOCKER_FULLTAG}
          docker image push ${DOCKER_FULLTAG}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
