name: Build Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build Image
        env:
          DOCKER_ORG: gayankanishka
          DOCKER_REPO: pizza-castle-menu-service
          DOCKER_TAG: latest
        run: |
          export DOCKER_FULLTAG="${DOCKER_ORG}/${DOCKER_REPO}:${DOCKER_TAG//\\//-}"
          docker build -t "$DOCKER_FULLTAG" .
          mkdir -p build/artifacts
          docker save "$DOCKER_FULLTAG" > build/artifacts/docker-image.tar
          echo "$DOCKER_FULLTAG" > build/artifacts/docker-tag

      - uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: build/artifacts
