name: Build Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup layer cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./src/API/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pizza-castle-menu-service:latest
          outputs: build/docker/artifacts/docker-image.tar

      - uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: build/docker/artifacts
